### ISSUE TITLE
BMC firmware for HUANANZHI X10X99 16D

### ISSUE THREAD

**Issue by Edgar-I** [greguu/bios#1]
**Note: This motherboard does need updated BMC for better fan control. Make sure you have updated the BMC SOC flash as well.**

Could you please give some hints on how and where to get new BMC firmware?

**Comment by greguu** [comment]
Best to check directly with Huananzhi on up to date files!
Their support is quite responsive if you get in touch with them via the official store chat on _AE_.

Use these at your own risk: 
[Official BMC firmware](https://drive.google.com/file/d/13n3X6cydaHWNnvgJijHUf6cQ-x7x8e5b/edit)
[Official BIOS X10X99-16D V1.3 23-10-24](https://drive.google.com/file/d/1R2hj4ygJ9yF1kbl6d4wDdewC35Riamzc/edit)

**Comment by Edgar-I** [comment]
Many thanks. JIC uploaded it to WebArchive

https://archive.org/details/bmc_20240917

**Comment by AleXr64** [comment]
Greetings. Are there any other versions of the bmc firmware? I'm trying to find a firmware with available SYS_FAN settings, against fixed ones (as in 2.06, which holds about 60% of the RPM)

**Comment by MACTEP434** [comment]
> Greetings. Are there any other versions of the bmc firmware? I'm trying to find a firmware with available SYS_FAN settings, against fixed ones (as in 2.06, which holds about 60% of the RPM)

 Hey! Do you find something?

**Comment by greguu** [comment]
Reached out to HUANANZHI again. They provided another link, but its the same BMC firmware version as far as I can tell: 
https://drive.google.com/file/d/10TfDoEwJyp7AUUKe_Ee5jQp6_RVhNesp/view?usp=sharing
Feel free to contact them directly with your issue, I am not affiliated with them in any way.

I am not sure about the SYS_FAN and if it is even configurable ? 
You can add 12V fan controller/s with a little temperature probe. Then they only spin if needed. Very affordable.

**Comment by NoHeadroom** [comment]
Just use ipmitools - 60 means 60% :
ipmitool -I lanplus -H "BMC-IP" -U admin -P admin raw 0x0e 0x65 0x00 60

**Comment by greguu** [comment]
Some clarification from HUANANZHI :

> There is a UID button here
<img width="652" height="396" alt="Image" src="https://github.com/user-attachments/assets/6234fbe7-a3ee-48ca-a6cf-ea48fd4ef9f0" /> 

> 8 FAN pins, with FAN2 and FAN6 being CPU fan pins. The default mode is temperature control mode, and the UID cannot be used to control or adjust the settings. The remaining FAN pins are system fan pins, with the default mode being temperature control mode, which can be adjusted via UID to 10%, 50%, or 100%.

The ipmitool commands are temporary and need some scripting. Beware of setting the speed too low ! 

Using the UID button, the setting is permanent it seems.
You need to press and hold the button for quite a while, the blue LED will come on, blink, then it will adjust the power to the SYS_FANs. Repeat to get to the next step. Not quite sure what step the temperature controlled mode is, assume its the one that comes after 100%. 



Correction, as far as I know its the CPU_FAN that is not controllable via BIOS, BMC/ipmitool or from OS level.
Appears to default to 50% as a baseline. Not sure if it actually scales up on very high temperatures....
