### ISSUE TITLE
Operating system freezes randomly.

### ISSUE THREAD

**Issue by y0u4u6e** [greguu/bios#2]
After flashing the BIOS, the system may freeze after a few hours randomly. What BIOS settings should I check?
The problem occurs only with firmware with turbo boost unlock.

**Comment by greguu** [comment]
There is no guarantee that using S3 turbo unlock or under-volting will result in a stable system!
Do this at your own risk! I do not support stability issues as every system is different!

However, you can try as a test:

- disable hyper-threading in BIOS
- flash a BIOS without under-volting, eg X10X9916DV13-0.bin, if stable, then work your way up by increasing the under-volting value.
- build your own BIOS by using the stock firmware and experiment! see this [guide](https://miyconst.github.io/hardware/cpu/intel/2023/11/18/tbu-s3turbotool.html)

Do this at your own risk! I do not support stability issues as every system is different!
